### ISSUE TITLE
Support orthographic projection (isometric 3d)

### ISSUE THREAD

**Issue by snadon** [janhohenheim/foxtrot#123]

**Comment by janhohenheim** [comment]
I suppose implementing a fixed angle should be easy, as long as this does not include hiding meshes in front of the player. For that we'd have to add some sort of dynamic alpha texture and I don't know how to do that yet.
This also involves changing the direction the player is moving when issuing a movement command. Using the absolute X and Z axis breaks arbitrary up vectors, so think of something better.

**Comment by janhohenheim** [comment]
Implemented on `main` now, simply scroll out :)
The current implementation has no angle offset or a camera independently movable from the character, but I feel like it's very easy to customize it in its current state to one's own needs.
