### ISSUE TITLE
The game sometimes gets stuck loading scene assets

### ISSUE THREAD

**Issue by janhohenheim** [janhohenheim/foxtrot#129]
~~Waiting with debugging until I get a response at https://github.com/NiklasEi/bevy_asset_loader/issues/108~~ See https://github.com/janhohenheim/foxtrot/pull/187

**Comment by janhohenheim** [comment]
![image](https://user-images.githubusercontent.com/9047632/220488208-ad326f99-9ed2-4b33-942e-e735863389ee.png)

**Comment by janhohenheim** [comment]
Maybe fixed by https://github.com/bevyengine/bevy/pull/7825

**Comment by gmorenz** [comment]
Just got this on latest master. So it appears not to have been fixed by the Bevy 0.10 update.

**Comment by janhohenheim** [comment]
I think this might be a Bevy bug. I'd need to create a minimal example to verify this, but it's a bit tricky, since it would have to run the `App` in a loop until it gets stuck.

**Comment by janhohenheim** [comment]
Opened a bug report in https://github.com/bevyengine/bevy/issues/8706

**Comment by dagit** [comment]
For some reason on my machine I get this issue about 50% of the time. I ran foxtrot under gdb and when it gets stuck, I noticed it just keeps creating threads that exit. When I interrupt it look at the stack it's waiting on fences in `ash`.

I don't know if any of that information is helpful, but it makes me wonder if some gpu related initialization is failing.

**Comment by janhohenheim** [comment]
Seems to be fixed by Assets V2
