### ISSUE TITLE
Support displacement mapping via shaders

### ISSUE THREAD

**Issue by janhohenheim** [janhohenheim/foxtrot#171]
I'm no expert on this, but we should be able to shift a vertex in the vertex shader by the displacement map's level in the normal direction

**Comment by nicopap** [comment]
Depending on your usecase, you might be interested in parallax mapping[1] (POM).

Usecase:
- :red_square:  **Terrain height map**: do not use POM for height map, in this case, it is indeed better to use a vertex shader, or even use a dedicated terrain plugin[2] for very large maps.
- :green_square: **Fancy textures**: POM is good for stuff like cobblestone, rocks, brickwork. It's like normal mapping, but with actual depth.

links:
- [1] https://github.com/nicopap/bevy_mod_paramap/
- [2] https://github.com/kurtkuehnert/bevy_terrain

**Comment by janhohenheim** [comment]
Thanks for the suggestion, your crate looks perferct for my use-case! Is there a way to automatically use a displacement map that is included in a GLTF, like how `StandardMaterial` imports normal and roughness maps from the GLTF?

**Comment by nicopap** [comment]
Annoyingly, the base GLTF spec doesn't include an height map (or bump map) <https://registry.khronos.org/glTF/specs/2.0/glTF-2.0.html#reference-material>. There is a proposal to extend the standard with such a texture here: https://github.com/KhronosGroup/glTF/pull/2196. though it does look like a lot of work is needed to get it merged.

Furthermore, it is bevy that loads the GLTF, so we are stuck with whatever material & textures it loads. I think generating a height map based on the normal map is possible ([see the TODO section of the README](https://github.com/nicopap/bevy_mod_paramap/#todo)) But doing that at runtime is a bit beyond what I find acceptable in terms of performance. This is where a bevy asset preprocessing pipeline would be useful (planned for 0.11 I think)

**Comment by nicopap** [comment]
So if by "at runtime" you mean "in user code" the answer currently is "yes". As long as we don't somehow push the depth map (for parallax mapping, we should talk about "depth map" over height map) into the gltf model, we'll have to somehow tell bevy to load height maps. Currently the only way to tell bevy anything is through code. cart has been talking about "meta files" for the future asset pipeline which could also fulfills this role.

Though, time to plug my normal2depth map plugin. :rocket: If your gltf comes with a normal map but not a depth map, you can now generate it! Nothing easier, use the `bevy_mod_n2dmap` crate and call `standard_material.generate_depth_map(&mut images_asset)` and now your material should have a depth map, enabling directly parallax mapping on it. <https://github.com/devildahu/n2dmap> :rocket:

**Comment by janhohenheim** [comment]
Woah, that crate sounds really useful, thanks! I'll be sure to use it once Bevy 0.11 rolls out.

**Comment by nicopap** [comment]
well, I've just started testing it and it doesn't work quite well yet. :sweat_smile: So I'd reserve judgement until it's complete.

**Comment by janhohenheim** [comment]
I decided that this is out of scope for the template
