### ISSUE TITLE
On windows there is a "Failed to load dialog" error when starting a dialog with the other fox.

### ISSUE THREAD

**Issue by MarcusSakae** [janhohenheim/foxtrot#208]
#### The error looks as follow: 

```
Failed to load dialog "dialogs/follower.dlg.ron": No such dialog. Available dialog: ["dialogs\\follower.dlg.ron"]
```

#### I'm think the error is because of this line:
https://github.com/janhohenheim/foxtrot/blob/683ae5153f8e5740e80acfb6baeb9e1c1122d2e4/src/world_interaction/dialog.rs#L50

The problem is probably that windows use slashes for path separators.

#### Suggested solution:
Fix windows, or it that fails maybe try a `std::path::Path` instead of format string with a slash in it.
maybe something along the lines of:
```rs
        let path = Path::new("dialogs")
            .join(&dialog_event.dialog.0)
            .with_extension("dlg.ron")
            .to_string_lossy()
            .to_string();
```

**Comment by janhohenheim** [comment]
Thanks for the report! Gonna push a fix in a couple hours
