### ISSUE TITLE
The editor camera is grey / does not work

### ISSUE THREAD

**Issue by janhohenheim** [janhohenheim/foxtrot#246]
Happened as soon as we switched to bevy_dolly
https://github.com/janhohenheim/foxtrot/pull/231

**Comment by BlackPhlox** [comment]
Hmm, I haven't gone through all your code yet but I think the camera needs the editor camera component (I'll check up on this tomorrow). 
[See component here](https://github.com/jakobhellermann/bevy_editor_pls/blob/b7f8a980f3fb226885ca73d98d8b878aa87ce3b8/crates/bevy_editor_pls_default_windows/src/cameras/mod.rs#L30)
