### ISSUE TITLE
Make game fullscreen

### ISSUE THREAD

**Issue by TimJentzsch** [janhohenheim/foxtrot#252]
Most games work better when they use fullscreen by default.
Especially in the browser this will look better.

## Resources

- [Bevy example on Window settings](https://github.com/bevyengine/bevy/blob/main/examples/window/window_settings.rs)
- [Bevy `WindowMode`](https://docs.rs/bevy/latest/bevy/window/enum.WindowMode.html)

**Comment by janhohenheim** [comment]
Thanks for all the PRs and issues you are creating / commenting on, I greatly appreaciate your input :)

**Comment by TimJentzsch** [comment]
Thank you for putting together such a great template!
I think this is an important step for the Bevy ecosystem :)

I hope to integrate it into [`cargo-bavy`](https://github.com/TimJentzsch/cargo-bavy) at some point, but I'm not yet sure exactly how.
