### ISSUE TITLE
Speed up CI

### ISSUE THREAD

**Issue by TimJentzsch** [janhohenheim/foxtrot#255]
The CI testing jobs seem to be very slow right now (about 4 minutes each), especially considering that we don't even have any tests.

I'm not 100% sure what is causing it to be so slow.
I noticed that it seems to re-download the nightly cargo components before executing the commands and that might be the issue.
Or the compilation is somehow still slow. That is unlikely though, as it is only building `foxtrot` itself and no dependencies (thanks to the caching).

**Comment by TimJentzsch** [comment]
Maybe the `nightly` target is not ideal for CI and we should specify a fixed version again?
I'm not sure if that would fix this issue.

**Comment by TimJentzsch** [comment]
The `zld` installation for macOS also adds 2 minutes, perhaps we can cache that.

Here is a reference CI run: <https://github.com/janhohenheim/foxtrot/actions/runs/4652567474/jobs/8232859998?pr=254>

**Comment by janhohenheim** [comment]
Do you think #260 will help with this?

**Comment by TimJentzsch** [comment]
While it might help, I don't think it will solve the problem.

**Comment by janhohenheim** [comment]
I noticed this line in the CI:
![image](https://github.com/janhohenheim/foxtrot/assets/9047632/08beb801-c632-4d9f-b288-c8da71d9856d)

do you think this might be related?

**Comment by janhohenheim** [comment]
Update again: I figured it out! #264
The Wasm build was clearing our `target` directory and invalidating the cache!
I also disabled multi-OS CIs because different OSs never really failed individually on CI but on release anyways (bundling and packaging a `.dmg`, for example).

I disabled Wasm and our build times are back in the range of ~5 min!
