### ISSUE TITLE
Can't run Cargo run.

### ISSUE THREAD

**Issue by Andycodesforyou** [janhohenheim/foxtrot#274]
Hey Can't do a cargo run. 

Basically it seems to go through crates and dependencies until it hits packed_simd_2 v0.3.8 then starts to read a bunch of error messages.

error: unrecognized platform-specific intrinsic function: `simd_shuffle2`
  --> /Users/user/.cargo/registry/src/index.crates.io-6f17d22bba15001f/packed_simd_2-0.3.8/src/codegen/llvm.rs:10:5
   |
10 |     pub fn simd_shuffle2<T, U>(x: T, y: T, idx: [u32; 2]) -> U;
   |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

error: unrecognized platform-specific intrinsic function: `simd_shuffle4`
  --> /Users/user/.cargo/registry/src/index.crates.io-6f17d22bba15001f/packed_simd_2-0.3.8/src/codegen/llvm.rs:11:5
   |
11 |     pub fn simd_shuffle4<T, U>(x: T, y: T, idx: [u32; 4]) -> U;
   |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

error: unrecognized platform-specific intrinsic function: `simd_shuffle8`
  --> /Users/user/.cargo/registry/src/index.crates.io-6f17d22bba15001f/packed_simd_2-0.3.8/src/codegen/llvm.rs:12:5
   |
12 |     pub fn simd_shuffle8<T, U>(x: T, y: T, idx: [u32; 8]) -> U;
   |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

error: unrecognized platform-specific intrinsic function: `simd_shuffle16`
  --> /Users/user/.cargo/registry/src/index.crates.io-6f17d22bba15001f/packed_simd_2-0.3.8/src/codegen/llvm.rs:13:5
   |
13 |     pub fn simd_shuffle16<T, U>(x: T, y: T, idx: [u32; 16]) -> U;
   |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

error: unrecognized platform-specific intrinsic function: `simd_shuffle32`
  --> /Users/user/.cargo/registry/src/index.crates.io-6f17d22bba15001f/packed_simd_2-0.3.8/src/codegen/llvm.rs:14:5
   |
14 |     pub fn simd_shuffle32<T, U>(x: T, y: T, idx: [u32; 32]) -> U;
   |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

error: unrecognized platform-specific intrinsic function: `simd_shuffle64`
  --> /Users/user/.cargo/registry/src/index.crates.io-6f17d22bba15001f/packed_simd_2-0.3.8/src/codegen/llvm.rs:15:5
   |
15 |     pub fn simd_shuffle64<T, U>(x: T, y: T, idx: [u32; 64]) -> U;

the site for this dependency acknowledges that this crate is currently broken as stated here. https://crates.io/crates/packed_simd_2. 

I tried just deleting it and rerunning cargo check/run but it keeps on reinstalling it so there seems no way fix the problem. Is this a problem with Bevy or is Foxtrot linked to outdated/broken dependencies/crates? Or is the problem with something else? I've run rustup update so everything should be up to date.

**Comment by janhohenheim** [comment]
Huh, thanks for the report. I'll check it out later and patch the dependency.

**Comment by sandmuel** [comment]
I've experienced compile issues due to dependencies too, although for me it's a different one that is giving me an issue.

**Comment by MickHarrigan** [comment]
I did some digging into this and it looks like the crate [Simba](https://github.com/dimforge/simba) is the issue as they updated the crate that is causing the problem ([packed_simd](https://crates.io/crates/packed_simd)) on their repo, but not on [crates.io](https://crates.io/crates/simba).

I could very well be wrong, but that is what I am finding while digging in these repos.

**Comment by Umzugskarton** [comment]
I was able to 'cargo run' successfully when removing the "simd-nightly" feature from the bevy_rapier3d dependency, but had very bad performance - perhaps due to this feature missing.

**Comment by coopbri** [comment]
Pinning the nightly version to an older build worked for me. I created a PR for this [here](https://github.com/janhohenheim/foxtrot/pull/277).
