### ISSUE TITLE
How can I use this with stable Rust?

### ISSUE THREAD

**Issue by ethereumdegen** [janhohenheim/foxtrot#300]
Please make this work with Rust Stable if possible or let me know how to switch to it   if possible !! 

Rust nightly is giving me all kinds of issues -- incremental compiler breaking and such

**Comment by janhohenheim** [comment]
The nightly version is pinned in the rust toolchain file to prevent just that. Did you remove or overwrite it?

If nightly reall doesn't work for you, just change the entry in the toolchain file to say stable and try to compile it. There shouldn't be too many nightly-only features that need fixing. 

Also mind that if you use the config described in .cargo/fast_builds_config.toml by renaming it to config.toml, it assumes nightly, but has instructions for how it to switch to stable.

Let me know if you run into any issues :)
