### ISSUE TITLE
replacing fox by a guy from mixamo.com

### ISSUE THREAD

**Issue by heydocode** [janhohenheim/foxtrot#309]
I want to replace the fox (player) by a guy from mixamo.com and replace the npc by another guy from mixamo.com.

All I ask for is to reply by a detailed instruction to how to add animations (from mixamo.com) to the guy of mixamo and how to assign the .glb obtained file to the player/npc

**Comment by janhohenheim** [comment]
I've never used Mixamo, as I do my own animations, so I can't really help there. But maybe another user knows how to help?

**Comment by ethereumdegen** [comment]
Yes! I am using mixamo animations with quaternious characters in bevy.   My game is here 

Doodlebuilt.com 

Hit me up in bevy discord (same alias ) for help i can even send any of you the base model.  Basically i spent 10 hours manually rerigging a quaternius character .  Deleted all the bones, placed new bones , re-mapped them to the mesh w new vertex weights, and got animations working w bevy.
