### ISSUE TITLE
Relicense to MIT + APACHE + CC0

### ISSUE THREAD

**Issue by janhohenheim** [janhohenheim/foxtrot#312]
Started by [this discussion on Discord](https://discord.com/channels/691052431525675048/937158127491633152/1250856626584551607), it seems like a template like Foxtrot would be better licensed under CC0. The main rationale is that users of the template should be able to license their games however they want, but the current situation *might* actually force them to use MIT/APACHE!

To get this done, I need the okay from the following contributors:

- [x] @janhohenheim 
- [x] @TimJentzsch 
- [x] @bash 
- [x] @PhaestusFox 
- [x] @EmiOnGit 

If your name is on this list, please copy-paste the following as a comment under this issue:

> I license past and future contributions under the CC0 license

The following contributors have helped with smaller edits and do in my opinion not need to give their consent for this relicense to be valid. It would be nice still if you could copy-paste the above as well, just to be sure :)

- [x] @0x0539 
- [x] @BlackPhlox 
- [x] @coopbri 
- [ ] @dvanderleij 
- [ ] @vijaypemmaraju 
- [ ] @MarcusSakae 

Update: per further discussion, the project should be triple-licensed like https://github.com/bevyengine/bevy_github_ci_template to effectively waive patent rights. Since all contributors have already agreed to the MIT and Apache licenses in the past, this should be no problem.

Update 2: Just to be sure:
I, Jan Hohenheim, hereby waive all patent rights to the Bevy game template known as "Foxtrot"

**Comment by bash** [comment]
I license past and future contributions under the CC0 license

**Comment by TimJentzsch** [comment]
I license past and future contributions under the CC0 license

**Comment by EmiOnGit** [comment]
I license past and future contributions under the CC0 license

**Comment by coopbri** [comment]
I license past and future contributions under the CC0 license

**Comment by 0x0539** [comment]
I license past and future contributions under the CC0 license

**Comment by janhohenheim** [comment]
Thanks everyone for answering really quickly so far :heart:

**Comment by coopbri** [comment]
@janhohenheim we have you to thank for such a useful and well-crafted FOSS template. You're the man!

**Comment by BlackPhlox** [comment]
I license past and future contributions under the CC0 license

**Comment by 0x0539** [comment]
+1, thank you Jan!

**Comment by PhaestusFox** [comment]
I license past and future contributions under the CC0 license

**Comment by janhohenheim** [comment]
Aww, thanks for the kind words everyone 😊 
Merging the relicense now 🎉
