### ISSUE TITLE
UI not showing

### ISSUE THREAD

**Issue by ptrkrlsrd** [janhohenheim/foxtrot#317]
Hey, I've been testing the template quite a lot and find it super useful, but I'm having one blocking problem which I can't seem to wrap my head around. I'm trying to spawn a basic TextBundle to start creating some game UI, but it seems like I can't see the text unless I hit Q and view it in the 2D viewport using the bevy_editor. 
Is there anything I have to have in mind when spawning TextBundles in combination with this setup regarding order of spawning, render layers or anything else?

**Comment by janhohenheim** [comment]
I've got an idea, give me a second

**Comment by janhohenheim** [comment]
Is it better after this commit? https://github.com/janhohenheim/foxtrot/commit/6cc5e38dee382eb338f7844db2ba31c62af19eb5

**Comment by janhohenheim** [comment]
Closing this for the moment since I'm 99% the linked commit fixes. Feel free to reopen otherwise :)

**Comment by ptrkrlsrd** [comment]
Hey, sorry for the late reply. Yes, that solved it. Thank you! 🙏

**Comment by janhohenheim** [comment]
@ptrkrlsrd great to hear :D
