### ISSUE TITLE
Migrate from XPBD to Avian if Avian & Oxidized Navigation is ready .

### ISSUE THREAD

**Issue by Jamamuuga** [janhohenheim/foxtrot#326]
Greetings, as XPBD is being discontinued, I've been migrating my new app based on this template to Avian and This & Oxidized Navigation are the last dependencies I have that don't have an Avian based version. Thanks for putting in the effort to migrate when you do! :D

**Comment by janhohenheim** [comment]
Definitely will. I'm waiting for the Blenvy release at the moment to start migration :)

**Comment by janhohenheim** [comment]
Closing this as a subset of https://github.com/janhohenheim/foxtrot/issues/327
