### ISSUE TITLE
Shadows dissapear after some distance

### ISSUE THREAD

**Issue by janhohenheim** [janhohenheim/foxtrot#49]
See https://github.com/bevyengine/bevy/issues/5789
Looks like we have to move the projection with the player / the camera (careful, don't inherit the camera's rotation!) or switch to a point light for the sunlight. Using multiple directional lights / one per object stacks the light and causes weirdness, don't try that.

**Comment by janhohenheim** [comment]
Looks like a native solution is on its way: https://github.com/bevyengine/bevy/pull/7064

**Comment by danchia** [comment]
Yes! Cascaded shadow maps should avoid the need to keep moving the shadow projection. You may still want to customize the maximum shadow distance, but that's relative to the viewing camera now, instead of some absolute volume.
