### ISSUE TITLE
Migrate custom dialog system to Yarn Spinner

### ISSUE THREAD

**Issue by janhohenheim** [janhohenheim/foxtrot#80]
[Yarn Spinner](https://yarnspinner.dev/), [Documentation](https://github.com/mystal/yharnam/tree/yarn_compiler)

See [Turn Your Writers Into Programmers: Greyboxing Narrative with Story Languages](https://www.youtube.com/watch?v=uh3ibbf8yAY)
Existing Yarn Spinner crates like [yharnam](https://github.com/mystal/yharnam) are outdated and don't support `.yarn` files directly.
Thus, this issue is blocked until someone (maybe me or @Mafii [wink wink nudge nudge ❤]) creates an up-to-date Yarn Spinner crate that includes a parser.

Update: We're implementing this right now!

**Comment by janhohenheim** [comment]
Update: the GDC talk [Turn Your Writers Into Programmers: Greyboxing Narrative with Story Languages](https://www.youtube.com/watch?v=uh3ibbf8yAY) recommends [Yarn Spinner](https://yarnspinner.dev/)

**Comment by Mafii** [comment]
On it, but very slowly 😊

**Comment by TimJentzsch** [comment]
Very interesting, I hadn't heard of Yarn Spinner before.
@Mafii if you are working on this in the open I'd be curious to take a look :)

**Comment by Mafii** [comment]
@TimJentzsch I'm not that far yet, however once I feel like I have something to show (even if not fully functional) I will make it open source and tag you! Thanks for the interest!

**Comment by TimJentzsch** [comment]
Thank you, I'm looking forward to it :)

**Comment by Mafii** [comment]
@TimJentzsch thanks to your CI setup and reviews, I felt comfortable to open-source the current state. 🎉 Thanks so much for the contributions!

While still in early development, it can be found here now: https://github.com/Mafii/rusty-yarn-spinner

**Comment by TimJentzsch** [comment]
The updated repository link is <https://github.com/yarn-slinger/yarn-slinger>
